package com.cambyze.banking.persistence.model;

import java.math.BigDecimal;
import java.util.LinkedHashSet;
import java.util.Set;
import org.hibernate.Hibernate;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;

/**
 * JPA entity for the bank account
 */
@Entity
@NamedEntityGraph(name = "graph.Account.operations",
    attributeNodes = @NamedAttributeNode("operations"))
@Table(name = "account")
public class Account {
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long accountId;
  private String bankAccountNumber;
  private int accountType;
  private BigDecimal balanceAmount;
  private BigDecimal overdraftAmount;
  @OneToMany(mappedBy = "account")
  private Set<Operation> operations = new LinkedHashSet<Operation>();

  private final static String GRAPH = "graph.Account.operations";

  /**
   * <p>
   * The BAN depends on the id to be unique but the id is only known after the insertion, because it
   * is generated by Hibernate/mySQL
   * </p>
   * <p>
   * To persist it is needed to save the update !!! No time to find a better solution :(
   * </p>
   */
  @PostPersist
  private void postPersist() {
    this.bankAccountNumber = "CAMBYZEBANK-" + this.accountId;
  }


  /**
   * Create a new bank account as a everyday bank account
   */

  public Account() {
    super();
    this.accountType = Constants.ACCOUNT_TYPE_BANK;
    this.balanceAmount = BigDecimal.valueOf(0.0);
    this.overdraftAmount = BigDecimal.valueOf(0.0);
  }

  // Overriding toString() method for a better description
  @Override
  public String toString() {
	  return this.accountId + " : " + this.bankAccountNumber + " + " + this.accountType + " + " + this.balanceAmount + " + " + this.overdraftAmount;
  }


  public String getGraph() {
    return GRAPH;
  }


  public Long getId() {
    return accountId;
  }

  public Long getBankAccountId() {
    return this.getId();
  }


  public String getBankAccountNumber() {
    return bankAccountNumber;
  }

  public int getAccountType() {
    return accountType;
  }

  public void setAccountType(int accountType) {
    this.accountType = accountType;
  }


  public BigDecimal getBalanceAmount() {
    return balanceAmount;
  }

  public void setBalanceAmount(BigDecimal balanceAmount) {
    this.balanceAmount = balanceAmount;
  }

  public BigDecimal getOverdraftAmount() {
    return overdraftAmount;
  }

  public void setOverdraftAmount(BigDecimal overdraftAmount) {
    this.overdraftAmount = overdraftAmount;
  }


  public Set<Operation> getBankingOperations() {
    Hibernate.initialize(this);
    return operations;
  }

}
