package com.cambyze.banking.persistence.model;

import java.math.BigDecimal;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PostPersist;

/**
 * JPA entity for the bank account
 */
@Entity
public class BankAccount {
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long id;
  private String bankAccountNumber;
  private int accountType;
  private BigDecimal balanceAmount;
  private BigDecimal overdraftAmount;

  /**
   * <p>
   * The BAN depends on the id to be unique but the id is only known after the insertion, because it
   * is generated by Hibernate/mySQL
   * </p>
   * <p>
   * To persist it is needed to save the update !!! No time to find a better solution :(
   * </p>
   */
  @PostPersist
  private void postPersist() {
    this.bankAccountNumber = "CAMBYZEBANK-" + this.id;
  }


  /**
   * Create a new bank account as a everyday bank account
   */

  public BankAccount() {
    super();
    this.accountType = Constants.ACCOUNT_TYPE_BANK;
    this.balanceAmount = BigDecimal.valueOf(0.0);
    this.overdraftAmount = BigDecimal.valueOf(0.0);
  }

  // Overriding toString() method for a better description
  @Override
  public String toString() {
    return this.id + " : " + this.bankAccountNumber + " + " + this.accountType + " + "
        + this.balanceAmount + " + " + this.overdraftAmount;
  }

  public Long getId() {
    return id;
  }

  public String getBankAccountNumber() {
    return bankAccountNumber;
  }

  public int getAccountType() {
    return accountType;
  }

  public BigDecimal getBalanceAmount() {
    return balanceAmount;
  }

  public BigDecimal getOverdraftAmount() {
    return overdraftAmount;
  }

}
