spring.application.name=banking-api

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=true

## MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/cambyze_banking


# JSON conversion setting
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Europe/Paris

## Logging
logging.level.com.cambyze=DEBUG

#java mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mailpr0ed0uard@gmail.com
spring.mail.password=tecltwyhrkmdxkgv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com