spring.application.name=services

## MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/cambyze_banking

## Logging
logging.level.com.cambyze=DEBUG

#java mail configuration
spring.application.name=Cambyze-banking
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mailpr0ed0uard@gmail.com
spring.mail.password=tecltwyhrkmdxkgv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
