#spring.application.name=services
#
### MongoDB
#spring.data.mongodb.uri=mongodb://localhost:27017/cambyze_banking
#
### Logging
#logging.level.com.cambyze=DEBUG
#
#### JavaMail
##spring.mail.host=mailtestdev11@gmail.com
#spring.mail.host=smtp.gmail.com
#
#spring.mail.port=587
##spring.mail.username=$mailtestdev11@gmail.com
#spring.mail.username=$phoenixetrey.com
##spring.mail.password=${MAIL_PASSWORD}
##spring.mail.password=$KaputDraconis1456*
#spring.mail.password=$
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


spring.mail.host=smtp.ionos.fr
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.ionos.fr