package com.cambyze.banking.persistence.services;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.cambyze.banking.persistence.dao.BankAccountRepository;
import com.cambyze.banking.persistence.model.BankAccount;

/**
 * DAO services to expose for the business services
 */
@Service
public class PersistenceServices {

  private static final Logger LOGGER = LoggerFactory.getLogger(PersistenceServices.class);

  @Autowired
  private BankAccountRepository bankAccountRepository;


  /**
   * Create a new bank account
   * 
   * @return its BAN
   */
  public String createNewBankAccount() {
    BankAccount ba = new BankAccount();
    bankAccountRepository.save(ba);
    LOGGER.debug("New BAN:" + ba.getBankAccountNumber());
    LOGGER.debug("New BA full content:" + ba.toString());
    // the creation of the BAN is done post insertion to have the id generated by Hibernate then we
    // have to save it twice - no time to find a better solution
    // TODO : find a better solution
    bankAccountRepository.save(ba);
    return ba.getBankAccountNumber();
  }


}
